import Footer from "@/lib/Layout/Footer";
import Header from "@/lib/Layout/Header";
import { Category, FooterItem, StrapiResponse } from "@/lib/types";
import { apiRequest } from "@/lib/utils";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function getCategories() {
  const categories = await apiRequest<StrapiResponse<Category>>(
    `${process.env.STRAPI_URL}/categories`
  );
  return categories.data;
}

async function getFooterItems() {
  const categories = await apiRequest<StrapiResponse<FooterItem>>(
    `${process.env.STRAPI_URL}/footeritems`
  );
  return categories.data;
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const categories = await getCategories();
  const footerItems = await getFooterItems();

  return (
    <html lang="es">
      <body>
        <Header categories={categories} />
        <main>{children}</main>
        <Footer menuItems={footerItems} />
      </body>
    </html>
  );
}
