import Footer from "@/lib/Layout/Footer";
import Header from "@/lib/Layout/Header";
import { apiRequest } from "@/lib/utils";
import type { Metadata } from "next";
import "./globals.css";
import { MenusResponse } from "@/lib/types";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const revalidate = 86400;

async function getMenus(): Promise<MenusResponse> {
  const menus = await apiRequest<MenusResponse>(`${process.env.WP_URL}/menus`);
  return menus;
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { primary, footer } = await getMenus();

  return (
    <html lang="es">
      <body>
        <Header menu={primary} />
        <main>{children}</main>
        <Footer menu={footer} />
      </body>
    </html>
  );
}
