import type { Metadata } from "next";
import { GoogleAnalytics } from "@next/third-parties/google";
import { getMenus } from "@/wp-link";
import "./globals.css";
import { Header, Main, Footer } from "@/lib/layout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const revalidate = 86400;

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { primary, footer } = await getMenus(process.env.WP_API_URL);

  return (
    <html lang="es">
      <GoogleAnalytics gaId="G-T7GJF4K2B9" />
      <body>
        <Header menu={primary} />
        <Main>{children}</Main>
        <Footer menu={footer} />
      </body>
    </html>
  );
}
